#! /bin/bash -i
config add ~/.bashrc
config add ~/.bash_profile
config add ~/.bash_logout
config add ~/.clang-format
config add ~/.gitconfig
config add ~/.config/nvim/init.lua
config add ~/.config/nvim/lua/
