#! /bin/bash
sudo pacman -Rns $(pacman -Qtdq) # 如上文所述，删除孤立软件包（常用）
# sudo pacman -Sc # 删除当前未安装的所有缓存包和未使用的同步数据库（可选）
sudo pacman -Scc # 从缓存中删除所有文件，这是最激进的方法，不会在缓存文件夹中留下任何内容（一般不使用）
paccache -r # 删除已安装和未安装包的所有缓存版本，但最近 3 个版本除外

# sudo paru -Sc # 删除当前未安装的所有缓存包和未使用的同步数据库（可选）
sudo paru -Sccd # 从缓存中删除所有文件，这是最激进的方法，不会在缓存文件夹中留下任何内容（一般不使用）
# rm -rf ~/.cache/yay

