#!/usr/bin/env bash
# paru -Qqem | grep kde | paru -S -a --rebuild --noconfirm -
# paru -Qqem | grep plasma | paru -S -a --rebuild --noconfirm -
paru -Qqe | grep kwin | paru -S -a --rebuild --noconfirm -
